1. With both tests I seemed to get an error that seems to be stemming from the version of python I am testing in..
The reason why I think that the two tests would be different is because when a session id is added, it allows the scanner to look for vulnerabilities with respect to a specific user and their information which isn't possible when scanning from the base url as there is not user created. (will fix issue tomorrow and attempt the tests again to see if i get a different output).

Logs:
C:\Users\lmilo\Documents>git clone https://github.com/pwn0sec/PwnXSS.git
Cloning into 'PwnXSS'...
remote: Enumerating objects: 151, done.
remote: Counting objects: 100% (151/151), done.
remote: Compressing objects: 100% (138/138), done.
remote: Total 151 (delta 55), reused 18 (delta 6), pack-reused 0
Receiving objects: 100% (151/151), 167.17 KiB | 2.04 MiB/s, done.
Resolving deltas: 100% (55/55), done.

C:\Users\lmilo\Documents>cd pwnxss

C:\Users\lmilo\Documents\PwnXSS>chmod 755 -R PwnXSS
'chmod' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\lmilo\Documents\PwnXSS>py pwnxss.py --help
←[1;32m██████╗ ██╗    ██╗███╗   ██╗██╗  ██╗███████╗███████╗
██╔══██╗██║    ██║████╗  ██║╚██╗██╔╝██╔════╝██╔════╝
██████╔╝██║ █╗ ██║██╔██╗ ██║ ╚███╔╝ ███████╗███████╗ ←[1;31m{v0.5 Final}←[1;32m
██╔═══╝ ██║███╗██║██║╚██╗██║ ██╔██╗ ╚════██║╚════██║ ←[4m←[1;36mhttps://github.com/pwn0sec/PwnXSS←[0m←[1;32m
██║     ╚███╔███╔╝██║ ╚████║██╔╝ ██╗███████║███████║
╚═╝      ╚══╝╚══╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝╚══════╝
<<<<<<< STARTING >>>>>>>

[←[1;33m23:05:00←[0m] [←[1;32mINFO←[0m] Starting PwnXSS...
usage: PwnXSS -u <target> [options]

Options:
  --help            Show usage and help parameters
  -u                Target url (e.g. http://testphp.vulnweb.com)
  --depth           Depth web page to crawl. Default: 2
  --payload-level   Level for payload Generator, 7 for custom payload. {1...6}. Default: 6
  --payload         Load custom payload directly (e.g. <script>alert(2005)</script>)
  --method          Method setting(s):
                        0: GET
                        1: POST
                        2: GET and POST (default)
  --user-agent      Request user agent (e.g. Chrome/2.1.1/...)
  --single          Single scan. No crawling just one address
  --proxy           Set proxy (e.g. {'https':'https://10.10.1.10:1080'})
  --about           Print information about PwnXSS tool
  --cookie          Set cookie (e.g {'ID':'1094200543'})

Github: https://www.github.com/pwn0sec/PwnXSS
Version: 0.5 Final

C:\Users\lmilo\Documents\PwnXSS>py pwnxss.py -u http://127.0.0.1:8081/
←[1;32m██████╗ ██╗    ██╗███╗   ██╗██╗  ██╗███████╗███████╗
██╔══██╗██║    ██║████╗  ██║╚██╗██╔╝██╔════╝██╔════╝
██████╔╝██║ █╗ ██║██╔██╗ ██║ ╚███╔╝ ███████╗███████╗ ←[1;31m{v0.5 Final}←[1;32m
██╔═══╝ ██║███╗██║██║╚██╗██║ ██╔██╗ ╚════██║╚════██║ ←[4m←[1;36mhttps://github.com/pwn0sec/PwnXSS←[0m←[1;32m
██║     ╚███╔███╔╝██║ ╚████║██╔╝ ██╗███████║███████║
╚═╝      ╚══╝╚══╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝╚══════╝
<<<<<<< STARTING >>>>>>>

[←[1;33m23:08:45←[0m] [←[1;32mINFO←[0m] Starting PwnXSS...
←[1;37m***************
[←[1;33m23:08:45←[0m] [←[1;32mINFO←[0m] Checking connection to: ←[1;33mhttp://127.0.0.1:8081/
[←[1;33m23:08:45←[0m] [←[1;32mINFO←[0m] Connection estabilished ←[1;32m200
[←[1;33m23:08:45←[0m] [←[1;33mWARNING←[0m] Target have form with POST method: ←[1;36mhttp://127.0.0.1:8081/
[←[1;33m23:08:45←[0m] [←[1;32mINFO←[0m] Collecting form input key.....
[←[1;33m23:08:45←[0m] [←[1;32mINFO←[0m] Internal error: 'type'
[←[1;33m23:08:45←[0m] [←[1;32mINFO←[0m] Form key name: ←[1;32mpassword←[0m value: ←[1;32m<script>prompt(document.cookie)</script>
[←[1;33m23:08:45←[0m] [←[1;32mINFO←[0m] Internal error: 'name'
[←[1;33m23:08:45←[0m] [←[1;32mINFO←[0m] Sending payload (POST) method...
[←[1;33m23:08:45←[0m] [←[1;32mINFO←[0m] Parameter page using (POST) payloads but not 100% yet...
←[1;37m***************
[←[1;33m23:08:46←[0m] [←[1;32mINFO←[0m] Checking connection to: ←[1;33mhttp://127.0.0.1:8081/
[←[1;33m23:08:46←[0m] [←[1;32mINFO←[0m] Connection estabilished ←[1;32m200
[←[1;33m23:08:46←[0m] [←[1;33mWARNING←[0m] Target have form with POST method: ←[1;36mhttp://127.0.0.1:8081/
[←[1;33m23:08:46←[0m] [←[1;32mINFO←[0m] Collecting form input key.....
[←[1;33m23:08:46←[0m] [←[1;32mINFO←[0m] Internal error: 'type'
[←[1;33m23:08:46←[0m] [←[1;32mINFO←[0m] Form key name: ←[1;32mpassword←[0m value: ←[1;32m<script>alert(6000/3000)</script>
[←[1;33m23:08:46←[0m] [←[1;32mINFO←[0m] Internal error: 'name'
[←[1;33m23:08:46←[0m] [←[1;32mINFO←[0m] Sending payload (POST) method...
[←[1;33m23:08:46←[0m] [←[1;32mINFO←[0m] Parameter page using (POST) payloads but not 100% yet...
Traceback (most recent call last):
  File "C:\Users\lmilo\Documents\PwnXSS\pwnxss.py", line 73, in <module>
    start()
  File "C:\Users\lmilo\Documents\PwnXSS\pwnxss.py", line 54, in start
    crawler.crawl(getopt.u,int(getopt.depth),getopt.proxy,getopt.user_agent,check(getopt),getopt.method,getopt.cookie)
  File "C:\Users\lmilo\Documents\PwnXSS\lib\crawler\crawler.py", line 50, in crawl
    self.crawl(url,depth-1,base,proxy,level,method,cookie)
  File "C:\Users\lmilo\Documents\PwnXSS\lib\crawler\crawler.py", line 42, in crawl
    urls=self.getLinks(base,proxy,headers,cookie)
  File "C:\Users\lmilo\Documents\PwnXSS\lib\crawler\crawler.py", line 19, in getLinks
    text=conn.get(base).text
  File "C:\Users\lmilo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\lmilo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\lmilo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 636, in send
    kwargs.setdefault('proxies', self.rebuild_proxies(request, self.proxies))
  File "C:\Users\lmilo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 289, in rebuild_proxies
    new_proxies = proxies.copy()
AttributeError: 'str' object has no attribute 'copy'

C:\Users\lmilo\Documents\PwnXSS>python pwnxss.py -u http://127.0.0.1:8081/| c:\users\lmilo\documents\test1output.txt
'c:\users\lmilo\documents\test1output.txt' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\lmilo\Documents\PwnXSS>python pwnxss.py -u http://127.0.0.1:8081/ | type c:\users\lmilo\documents\test1output.txt
The system cannot find the file specified.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

C:\Users\lmilo\Documents\PwnXSS>py pwnxss.py -u http://127.0.0.1:8081/ | type c:\users\lmilo\documents\test1output.txt
The system cannot find the file specified.
Traceback (most recent call last):
  File "C:\Users\lmilo\Documents\PwnXSS\pwnxss.py", line 73, in <module>
    start()
  File "C:\Users\lmilo\Documents\PwnXSS\pwnxss.py", line 49, in start
    print(logo)
  File "C:\Users\lmilo\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 7-13: character maps to <undefined>

C:\Users\lmilo\Documents\PwnXSS>py pwnxss.py -u http://127.0.0.1:8081/
←[1;32m██████╗ ██╗    ██╗███╗   ██╗██╗  ██╗███████╗███████╗
██╔══██╗██║    ██║████╗  ██║╚██╗██╔╝██╔════╝██╔════╝
██████╔╝██║ █╗ ██║██╔██╗ ██║ ╚███╔╝ ███████╗███████╗ ←[1;31m{v0.5 Final}←[1;32m
██╔═══╝ ██║███╗██║██║╚██╗██║ ██╔██╗ ╚════██║╚════██║ ←[4m←[1;36mhttps://github.com/pwn0sec/PwnXSS←[0m←[1;32m
██║     ╚███╔███╔╝██║ ╚████║██╔╝ ██╗███████║███████║
╚═╝      ╚══╝╚══╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝╚══════╝
<<<<<<< STARTING >>>>>>>

[←[1;33m23:13:22←[0m] [←[1;32mINFO←[0m] Starting PwnXSS...
←[1;37m***************
[←[1;33m23:13:22←[0m] [←[1;32mINFO←[0m] Checking connection to: ←[1;33mhttp://127.0.0.1:8081/
[←[1;33m23:13:22←[0m] [←[1;32mINFO←[0m] Connection estabilished ←[1;32m200
[←[1;33m23:13:22←[0m] [←[1;33mWARNING←[0m] Target have form with POST method: ←[1;36mhttp://127.0.0.1:8081/
[←[1;33m23:13:22←[0m] [←[1;32mINFO←[0m] Collecting form input key.....
[←[1;33m23:13:22←[0m] [←[1;32mINFO←[0m] Internal error: 'type'
[←[1;33m23:13:22←[0m] [←[1;32mINFO←[0m] Form key name: ←[1;32mpassword←[0m value: ←[1;32m<script>alert(6000/3000)</script>
[←[1;33m23:13:22←[0m] [←[1;32mINFO←[0m] Internal error: 'name'
[←[1;33m23:13:22←[0m] [←[1;32mINFO←[0m] Sending payload (POST) method...
[←[1;33m23:13:22←[0m] [←[1;32mINFO←[0m] Parameter page using (POST) payloads but not 100% yet...
←[1;37m***************
[←[1;33m23:13:23←[0m] [←[1;32mINFO←[0m] Checking connection to: ←[1;33mhttp://127.0.0.1:8081/
[←[1;33m23:13:23←[0m] [←[1;32mINFO←[0m] Connection estabilished ←[1;32m200
[←[1;33m23:13:23←[0m] [←[1;33mWARNING←[0m] Target have form with POST method: ←[1;36mhttp://127.0.0.1:8081/
[←[1;33m23:13:23←[0m] [←[1;32mINFO←[0m] Collecting form input key.....
[←[1;33m23:13:23←[0m] [←[1;32mINFO←[0m] Internal error: 'type'
[←[1;33m23:13:23←[0m] [←[1;32mINFO←[0m] Form key name: ←[1;32mpassword←[0m value: ←[1;32m<script>prompt(5000/200)</script>
[←[1;33m23:13:23←[0m] [←[1;32mINFO←[0m] Internal error: 'name'
[←[1;33m23:13:23←[0m] [←[1;32mINFO←[0m] Sending payload (POST) method...
[←[1;33m23:13:23←[0m] [←[1;32mINFO←[0m] Parameter page using (POST) payloads but not 100% yet...
Traceback (most recent call last):
  File "C:\Users\lmilo\Documents\PwnXSS\pwnxss.py", line 73, in <module>
    start()
  File "C:\Users\lmilo\Documents\PwnXSS\pwnxss.py", line 54, in start
    crawler.crawl(getopt.u,int(getopt.depth),getopt.proxy,getopt.user_agent,check(getopt),getopt.method,getopt.cookie)
  File "C:\Users\lmilo\Documents\PwnXSS\lib\crawler\crawler.py", line 50, in crawl
    self.crawl(url,depth-1,base,proxy,level,method,cookie)
  File "C:\Users\lmilo\Documents\PwnXSS\lib\crawler\crawler.py", line 42, in crawl
    urls=self.getLinks(base,proxy,headers,cookie)
  File "C:\Users\lmilo\Documents\PwnXSS\lib\crawler\crawler.py", line 19, in getLinks
    text=conn.get(base).text
  File "C:\Users\lmilo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\lmilo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\lmilo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 636, in send
    kwargs.setdefault('proxies', self.rebuild_proxies(request, self.proxies))
  File "C:\Users\lmilo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 289, in rebuild_proxies
    new_proxies = proxies.copy()
AttributeError: 'str' object has no attribute 'copy'

C:\Users\lmilo\Documents\PwnXSS>py
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z


C:\Users\lmilo\Documents\PwnXSS>py pwnxss.py -u http://127.0.0.1:8081/ --cookie='{"session":"127.0.0.1"}'
←[1;32m██████╗ ██╗    ██╗███╗   ██╗██╗  ██╗███████╗███████╗
██╔══██╗██║    ██║████╗  ██║╚██╗██╔╝██╔════╝██╔════╝
██████╔╝██║ █╗ ██║██╔██╗ ██║ ╚███╔╝ ███████╗███████╗ ←[1;31m{v0.5 Final}←[1;32m
██╔═══╝ ██║███╗██║██║╚██╗██║ ██╔██╗ ╚════██║╚════██║ ←[4m←[1;36mhttps://github.com/pwn0sec/PwnXSS←[0m←[1;32m
██║     ╚███╔███╔╝██║ ╚████║██╔╝ ██╗███████║███████║
╚═╝      ╚══╝╚══╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝╚══════╝
<<<<<<< STARTING >>>>>>>

[←[1;33m23:27:47←[0m] [←[1;32mINFO←[0m] Starting PwnXSS...
←[1;37m***************
Traceback (most recent call last):
  File "C:\Users\lmilo\Documents\PwnXSS\pwnxss.py", line 73, in <module>
    start()
  File "C:\Users\lmilo\Documents\PwnXSS\pwnxss.py", line 52, in start
    core.main(getopt.u,getopt.proxy,getopt.user_agent,check(getopt),getopt.cookie,getopt.method)
  File "C:\Users\lmilo\Documents\PwnXSS\lib\core.py", line 163, in main
    self.session=session(proxy,headers,cookie)
  File "C:\Users\lmilo\Documents\PwnXSS\lib\helper\helper.py", line 26, in session
    r.cookies.update(json.loads(cookie))
  File "C:\Users\lmilo\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\lmilo\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\lmilo\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

C:\Users\lmilo\Documents\PwnXSS>